### ISSUE TITLE
Do console errors reference the correct character position?

### ISSUE THREAD

**Issue by dougajmcdonald** [corewar/corewar#163]
If you type in `M` on it's own it says 
line: 1
char: 2
ERROR
Expected 'opcode', got end of file

Is character `2`  right? If it's meant to imply that character 2 (in that example) is intended to be the end of the opcode then I guess it makes sense.
If it's intended to imply that character 2 is an error then it's a little more confusing. 

The more I read it I suspect the former, in which case probably not a problem!

**Comment by gareththegeek** [comment]
I believe this is a duplicate of #127

**Comment by gareththegeek** [comment]
Closing, duplicate.
